# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shutdown.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(625, 307)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(100, 245, 75, 23))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_30 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_30.setGeometry(QtCore.QRect(20, 155, 131, 23))
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_60 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_60.setGeometry(QtCore.QRect(20, 185, 131, 23))
        self.pushButton_60.setObjectName("pushButton_60")
        self.pushButton_stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_stop.setGeometry(QtCore.QRect(15, 85, 131, 41))
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(45, 35, 71, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_timer = QtWidgets.QLabel(self.centralwidget)
        self.label_timer.setGeometry(QtCore.QRect(15, 55, 126, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_timer.setFont(font)
        self.label_timer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_timer.setObjectName("label_timer")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(350, 240, 111, 16))
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(15, 135, 141, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(170, 10, 20, 261))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(305, 10, 51, 16))
        self.label.setObjectName("label")
        self.lineEdit_serveraddr = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_serveraddr.setGeometry(QtCore.QRect(500, 40, 111, 20))
        self.lineEdit_serveraddr.setObjectName("lineEdit_serveraddr")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(438, 40, 61, 21))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(200, 45, 41, 21))
        self.label_5.setObjectName("label_5")
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(240, 45, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_status.setFont(font)
        self.label_status.setObjectName("label_status")
        self.pushButton_connect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_connect.setGeometry(QtCore.QRect(335, 45, 75, 23))
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.listView_clients = QtWidgets.QListView(self.centralwidget)
        self.listView_clients.setGeometry(QtCore.QRect(190, 85, 156, 131))
        self.listView_clients.setObjectName("listView_clients")
        self.pushButton_remote_sd_custom = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_remote_sd_custom.setGeometry(QtCore.QRect(360, 105, 101, 21))
        self.pushButton_remote_sd_custom.setObjectName("pushButton_remote_sd_custom")
        self.lineEdit_remote_time = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_remote_time.setGeometry(QtCore.QRect(465, 105, 31, 20))
        self.lineEdit_remote_time.setObjectName("lineEdit_remote_time")
        self.pushButton_minShutdown = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_minShutdown.setGeometry(QtCore.QRect(20, 215, 101, 21))
        self.pushButton_minShutdown.setObjectName("pushButton_minShutdown")
        self.lineEdit_shutdownTime = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_shutdownTime.setGeometry(QtCore.QRect(125, 215, 26, 20))
        self.lineEdit_shutdownTime.setObjectName("lineEdit_shutdownTime")
        self.pushButton_remote_sd_now = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_remote_sd_now.setGeometry(QtCore.QRect(360, 135, 136, 23))
        self.pushButton_remote_sd_now.setObjectName("pushButton_remote_sd_now")
        self.pushButton_remote_sd_stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_remote_sd_stop.setGeometry(QtCore.QRect(360, 165, 136, 23))
        self.pushButton_remote_sd_stop.setObjectName("pushButton_remote_sd_stop")
        self.pushButton_refresh_clients = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_refresh_clients.setGeometry(QtCore.QRect(215, 225, 96, 23))
        self.pushButton_refresh_clients.setObjectName("pushButton_refresh_clients")
        self.lineEdit_clientName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_clientName.setGeometry(QtCore.QRect(500, 15, 111, 20))
        self.lineEdit_clientName.setObjectName("lineEdit_clientName")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(438, 15, 61, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(65, 10, 51, 16))
        self.label_7.setObjectName("label_7")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(430, 65, 191, 10))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(420, 5, 16, 56))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 625, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_exit.setText(_translate("MainWindow", "Exit !"))
        self.pushButton_30.setText(_translate("MainWindow", "ShutDown in 30 min !"))
        self.pushButton_60.setText(_translate("MainWindow", "ShutDown in 60 min !"))
        self.pushButton_stop.setText(_translate("MainWindow", "Stop pending operation!"))
        self.label_3.setText(_translate("MainWindow", "Shutdown in"))
        self.label_timer.setText(_translate("MainWindow", "00:00:00"))
        self.label_4.setText(_translate("MainWindow", "by Luna per l\'amore !"))
        self.label.setText(_translate("MainWindow", "Network"))
        self.lineEdit_serveraddr.setText(_translate("MainWindow", "DESKTOP-TTCCQR0"))
        self.label_2.setText(_translate("MainWindow", "Server addr"))
        self.label_5.setText(_translate("MainWindow", "Status:"))
        self.label_status.setText(_translate("MainWindow", "Disconnected"))
        self.pushButton_connect.setText(_translate("MainWindow", "Connect!"))
        self.pushButton_remote_sd_custom.setText(_translate("MainWindow", "ShutDown in (min)"))
        self.lineEdit_remote_time.setText(_translate("MainWindow", "45"))
        self.pushButton_minShutdown.setText(_translate("MainWindow", "ShutDown in (min)"))
        self.lineEdit_shutdownTime.setText(_translate("MainWindow", "45"))
        self.pushButton_remote_sd_now.setText(_translate("MainWindow", "ShutDown Now!"))
        self.pushButton_remote_sd_stop.setText(_translate("MainWindow", "Stop pending operation"))
        self.pushButton_refresh_clients.setText(_translate("MainWindow", "Refresh Clients"))
        self.lineEdit_clientName.setText(_translate("MainWindow", "DESKTOP-ALE"))
        self.label_6.setText(_translate("MainWindow", "Client name"))
        self.label_7.setText(_translate("MainWindow", "Locale"))

